name: 'Deploy Nikola to GitHub Pages'
on:
  push:
    branches:
      - src

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      # === Explicitly run git config before the nikola-action ===
      - name: Set safe Git directory for Nikola
        run: git config --global --add safe.directory /github/workspace
      # ==========================================================

      - name: Build and Deploy Nikola
        uses: getnikola/nikola-action@v2
