on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Deploy Nikola
        uses: ./.github/actions/nikola-deploy
        with:
          dry_run: false
