on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Set safe Git directory
      run: git config --global --add safe.directory /github/workspace

    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v2